#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "revealjs"
name = "Revealjs"
description.en = "Create Stunning Presentations on the Web"
description.fr = "Créez de superbes présentations sur le web"

version = "5.1.0~ynh1"

maintainers = ["limezy"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "MIT"
website = "https://revealjs.com"
demo = "https://revealjs.com/?demo"
admindoc = "https://revealjs.com"
userdoc = "https://revealjs.com"
code = "https://github.com/hakimel/reveal.js"
fund = "https://slides.com"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/hakimel/reveal.js/archive/refs/tags/5.1.0.tar.gz"
    sha256 = "ddc83539ec50583eac9a972e88f892971b37c44e70dd0c08be069e2688684b71"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

